### PR TITLE
Control parameter

### LINKED ISSUE #4: Control parameter?
Maybe add a control parameter?

https://github.com/ilyakurdyukov/jpeg-quantsmooth/blob/c643e9f4a1f7c24851e03f19644aced021a76fd6/quantsmooth.h#L372-L373

To:
```c
add = coef1 - a0;
add -= roundf(a2);
add *= coefgain; // double coefgain >= 0.0
```

### PR DESCRIPTION
**Pull request by zvezdochiot**
0.20200127: fix #4: Control parameter

PS: I warned about "dirty hands".

### CODE REVIEW

**Comment by zvezdochiot** [comment]
Oops! Description of options in README forgot to add.

**Comment by ilyakurdyukov** [comment]
Hey, you can do experiments in your own fork. I'll take it, if it were really useful.

**Comment by ilyakurdyukov** [comment]
You have fork here: https://github.com/ImageProcessing-ElectronicPublications/jpeg-quantsmooth
So periodically I'll look at what you are doing here.

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>I'll look at what you are doing here.

Ok. I open issue again.

**Pull request closed without merging**
