### PR TITLE
Fix build on Darwin powerpc

### PR DESCRIPTION
**Pull request by barracuda156**
Minor fixes to Makefile

### CODE REVIEW

**Comment by ilyakurdyukov** [comment]
`clang++`, seriously? This project is in pure C.

How about `ifneq (,$(filter ppc%,$(ARCH)))` ?

**Comment by barracuda156** [comment]
@ilyakurdyukov That was a copy-paste typo, I am sorry :) Fixed now.

**Comment by barracuda156** [comment]
> How about `ifneq (,$(filter ppc%,$(ARCH)))` ?

@ilyakurdyukov That won’t work, because it uses `uname -m` to get `ARCH`, which returns “Power Macintosh”.

P. S. `-march` is not supported on powerpc on _any_ platform, however I just do not know what is the way to detect it on *BSD etc. Could you suggest how to make it inclusive of all possible options?

**Comment by barracuda156** [comment]
Here is what I get:
```
36-233% uname -m
Power Macintosh
36-233% uname -p
powerpc
```

**Comment by ilyakurdyukov** [comment]
But it's `ppc*` on Linux.

I want to commit the patch below, will it work for you?

```patch
diff --git a/Makefile b/Makefile
index 97c9461..761331e 100644
--- a/Makefile
+++ b/Makefile
@@ -25,10 +25,10 @@ SIMDOBJ := jpegqs_base.o jpegqs_sse2.o jpegqs_avx2.o jpegqs_avx512.o
 else ifeq ($(SIMD),none)
 SIMDFLG := -DNO_SIMD
 else ifeq ($(SIMD),native)
-ifneq (,$(filter arm% aarch64,$(ARCH)))
-SIMDFLG := -mcpu=native
+ifneq (,$(filter arm% aarch64 ppc% Power\ Macintosh,$(ARCH)))
+SIMDFLG := -mcpu=native -mtune=native
 else
-SIMDFLG := -march=native
+SIMDFLG := -march=native -mtune=native
 endif
 else ifeq ($(SIMD),avx512)
 SIMDFLG := $(SIMD_AVX512)
@@ -52,7 +52,11 @@ endif
 ifeq ($(OS),Darwin)
 LDFLAGS := -Wl,-dead_strip
 ifeq ($(LIBMINIOMP),)
+ifneq (,$(findstring clang,$(notdir $(CC))))
 LDFLAGS += -lomp
+else
+LDFLAGS += -lgomp
+endif
 endif
 else
 LDFLAGS := -Wl,--gc-sections -s
```

**Comment by barracuda156** [comment]
@ilyakurdyukov Yes, your patch works. Should I close this PR now?

**Comment by ilyakurdyukov** [comment]
I still don't like this condition:

```makefile
ifneq (,$(findstring clang,$(notdir $(CC))))
```

Can you tell me what kind of system you have? Why does MacOS use another compiler instead of Clang? What compiler is it, is it installed by default or do you specify your own `CC=` when calling make.

I suspect that for MacOS it would be better to make an exception not for Clang, but for an alternative compiler. Otherwise it will break the build for some users.

**Comment by barracuda156** [comment]
Both clang and gcc work and can be used on macOS. Xcode uses gcc prior to 10.7 and clang after. Here, however, a likely pick will be a non-Apple compiler, since neither archaic Xcode gcc nor later Xcode clangs support OpenMP. So, for example, MacPorts by default picks clang-17 on recent macOS versions and gcc-14 on old ones (but gcc works on all macOS versions).
In result we just need any clang to use `libomp` and any gcc to use `libgomp` (on macOS at least).

P. S. I was building with gcc-14, which is why I got the error, since I do not have `libomp` installed and gcc does not need it for OpenMP.

**Comment by ilyakurdyukov** [comment]
The problem is that for me in Linux `$(CC)` has the value `cc`. What will be the value in macOS which uses Clang? If `cc` will be a link to Clang, then this condition will not work correctly. Clang is more common in macOS.

```sh
$ echo '$(info $(CC))' | make -f /dev/stdin
cc
make: *** No targets.  Stop.
```

I don't have any macOS devices. Is it really necessary to specify the OpenMP library? In Linux it works without this.

**Comment by barracuda156** [comment]
On Sonoma (and perhaps any recent macOS) `CC` defaults to `clang`:
```
% echo "$(CC)"
clang: error: no input files
```
(As I mentioned above though, Xcode compilers are probably irrelevant when OpenMP is needed.)

> Is it really necessary to specify the OpenMP library? In Linux it works without this.

GCC normally does not need `-lgomp` passed explicitly, however here it failed for me without that (I have encountered 1–2 cases of a similar behavior elsewhere, but it is uncommon).
Clang typically needs an explicit flag, but a build environment should take care of it (since `libomp` is not a part of macOS, there is no default location for it either, it will depend on which package manager is used or where a user installed it manually; i.e. it may not be sufficient just to pass `-lomp` anyway).

Maybe just supply a variable which can be defined by a user or downstream distribution? Something `$(OPENMP_LDFLAG)`, and then neither compile-time tests are needed nor patches the source to fix flags.

**Comment by ilyakurdyukov** [comment]
```
% echo "$(CC)"
clang: error: no input files
```

You should do `$(info $(CC))` in makefile because it's not the same thing in the shell.

> Maybe just supply a variable which can be defined by a user or downstream distribution?

Ok, but with a shorter name, maybe something like `OMPLINK`?

**Comment by barracuda156** [comment]
Yeah, I tend to think a variable is a preferable solution, since there is no way to know where a user may have `libomp` installed. BTW, a variable is also needed for includes (gcc does not need it, only clang will, but with gcc it can just be left undefined, that will work).

**Comment by ilyakurdyukov** [comment]
Will this be sufficient? I'm not sure that Сlang detection will work properly.

What does $(CC) look like when you compile with GCC?

```patch
diff --git a/Makefile b/Makefile
index 97c9461..675ee18 100644
--- a/Makefile
+++ b/Makefile
@@ -25,10 +25,10 @@ SIMDOBJ := jpegqs_base.o jpegqs_sse2.o jpegqs_avx2.o jpegqs_avx512.o
 else ifeq ($(SIMD),none)
 SIMDFLG := -DNO_SIMD
 else ifeq ($(SIMD),native)
-ifneq (,$(filter arm% aarch64,$(ARCH)))
-SIMDFLG := -mcpu=native
+ifneq (,$(filter arm% aarch64 ppc% Power\ Macintosh,$(ARCH)))
+SIMDFLG := -mcpu=native -mtune=native
 else
-SIMDFLG := -march=native
+SIMDFLG := -march=native -mtune=native
 endif
 else ifeq ($(SIMD),avx512)
 SIMDFLG := $(SIMD_AVX512)
@@ -49,14 +49,18 @@ CFLAGS := -Wall -O2
 ifneq (,$(filter e2k,$(ARCH)))
 CFLAGS := $(filter-out -O2,$(CFLAGS)) -O3
 endif
+OMPLINK =
 ifeq ($(OS),Darwin)
 LDFLAGS := -Wl,-dead_strip
 ifeq ($(LIBMINIOMP),)
-LDFLAGS += -lomp
+# use -lgomp for GCC
+OMPLINK = -lomp
+endif
 endif
 else
 LDFLAGS := -Wl,--gc-sections -s
 endif
+LDFLAGS += $(OMPLINK)
 
 CFLAGS_LIB := $(CFLAGS) $(MFLAGS) $(SIMDFLG)
 CFLAGS_APP := $(CFLAGS_LIB) -Wextra -pedantic $(MTOPTS)
```

**Comment by barracuda156** [comment]
@ilyakurdyukov It looks like this will override value of `OMPLINK` even if I set it to `-lgomp` since there is no check if it has already been defined. Can a condition be added? It is fine to default to `-lomp` (we assume that more users have clang), but it will be better to avoid a need to patch the makefile.

MacPorts sets CC to the exact compiler path. I.e., it will be `/opt/local/bin/gcc-mp-14` on my system, or `/opt/local/bin/clang-17` on a modern macOS. Since _some_ OpenMP implementation is needed, Xcode `gcc` or `cc` won’t work.

**Comment by ilyakurdyukov** [comment]
Anything set this way is overridden by the command line definition, unless you use the `override` keyword.

```make
OMPLINK = -lomp
$(info OMPLINK: $(OMPLINK))
override OMPLINK = -lomp
$(info overriden OMPLINK: $(OMPLINK))
```

```
$ make OMPLINK=-lgomp
OMPLINK: -lgomp
overriden OMPLINK: -lomp
make: *** No targets.  Stop.
```

**Comment by ilyakurdyukov** [comment]
> /opt/local/bin/gcc-mp-14

Then try this patch:

```patch
diff --git a/Makefile b/Makefile
index 97c9461..cbc7c4e 100644
--- a/Makefile
+++ b/Makefile
@@ -25,10 +25,10 @@ SIMDOBJ := jpegqs_base.o jpegqs_sse2.o jpegqs_avx2.o jpegqs_avx512.o
 else ifeq ($(SIMD),none)
 SIMDFLG := -DNO_SIMD
 else ifeq ($(SIMD),native)
-ifneq (,$(filter arm% aarch64,$(ARCH)))
-SIMDFLG := -mcpu=native
+ifneq (,$(filter arm% aarch64 ppc% Power\ Macintosh,$(ARCH)))
+SIMDFLG := -mcpu=native -mtune=native
 else
-SIMDFLG := -march=native
+SIMDFLG := -march=native -mtune=native
 endif
 else ifeq ($(SIMD),avx512)
 SIMDFLG := $(SIMD_AVX512)
@@ -49,14 +49,20 @@ CFLAGS := -Wall -O2
 ifneq (,$(filter e2k,$(ARCH)))
 CFLAGS := $(filter-out -O2,$(CFLAGS)) -O3
 endif
+OMPLINK :=
 ifeq ($(OS),Darwin)
 LDFLAGS := -Wl,-dead_strip
 ifeq ($(LIBMINIOMP),)
-LDFLAGS += -lomp
+ifneq (,$(filter gcc%,$(notdir $(CC))))
+OMPLINK := -lgomp
+else
+OMPLINK := -lomp
+endif
 endif
 else
 LDFLAGS := -Wl,--gc-sections -s
 endif
+LDFLAGS += $(OMPLINK)
 
 CFLAGS_LIB := $(CFLAGS) $(MFLAGS) $(SIMDFLG)
 CFLAGS_APP := $(CFLAGS_LIB) -Wextra -pedantic $(MTOPTS)
```

**Comment by barracuda156** [comment]
Yes, this works for me:
```
--->  Building jpeg-quantsmooth
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/jpeg-quantsmooth-1.20240129" && /usr/bin/make -j6 -w all CC="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/compwrap/cc/opt/local/bin/gcc-mp-14" CXX="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/compwrap/cxx/opt/local/bin/g++-mp-14" OBJC="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/compwrap/objc/opt/local/bin/gcc-mp-14" OBJCXX="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/compwrap/objcxx/opt/local/bin/g++-mp-14" FC="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/compwrap/fc/opt/local/bin/gfortran-mp-14" F77="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/compwrap/f77/opt/local/bin/gfortran-mp-14" F90="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/compwrap/f90/opt/local/bin/gfortran-mp-14" INSTALL="/usr/bin/install -c" 
make: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/jpeg-quantsmooth-1.20240129'
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/compwrap/cc/opt/local/bin/gcc-mp-14 -Os -arch ppc  -mcpu=native -mtune=native -Wextra -pedantic -Xpreprocessor -fopenmp  -DAPPNAME=jpegqs -o jpegqs quantsmooth.c -ljpeg  -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc -lgomp -lm
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/compwrap/cc/opt/local/bin/gcc-mp-14 -Os -arch ppc  -mcpu=native -mtune=native -Wextra -pedantic -Xpreprocessor -fopenmp  -c -o libjpegqs.o libjpegqs.c
ar -rsc libjpegqs.a libjpegqs.o
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/compwrap/cc/opt/local/bin/gcc-mp-14 -Os -arch ppc  -mcpu=native -mtune=native -Wextra -pedantic -Xpreprocessor -fopenmp  -fPIC -shared -ljpeg  -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc -lgomp -o libjpegqs.dylib libjpegqs.o
make: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_jpeg-quantsmooth/jpeg-quantsmooth/work/jpeg-quantsmooth-1.20240129'
```

**Pull request closed without merging**
